export const FETCH_CASES = "FETCH_CASES";
export const FETCH_CASES_SUCCESS = "FETCH_CASES_SUCCESS";
export const FETCH_CASES_FAIL = "FETCH_CASES_FAIL";

export const FETCH_FLAG = "FETCH_FLAG";
export const FETCH_FLAG_SUCCESS = "FETCH_FLAG_SUCCESS";
export const FETCH_FLAG_FAIL = "FETCH_FLAG_FAIL";

export const FETCH_WORLD_CASE = "FETCH_WORLD_CASE";
export const FETCH_WORLD_CASE_SUCCESS = "FETCH_WORLD_CASE_SUCCESS";
export const FETCH_WORLD_CASE_FAIL = "FETCH_WORLD_CASE_FAIL";
